name: Lint Commit Messages

on: [pull_request]
permissions:
  contents: read

jobs:
  commitlint:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # for wagoid/commitlint-github-action to get commits in PR

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6
        with:
          configFile: "./.github/commitlint.config.mjs"
